services:
  hgss_pt_install_guide:
    image: hgss_pt_install_guide:latest
    container_name: hgss_pt_install_guide
    ports:
      - "8080:8080"
    volumes:
      - "D:/Dev/hgss_ace_install_instructions:/home/rebs/dev"
    tty: true
